[build]
  base = "."
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_SERVER_URL = "https://live-polling-backend-production-8ab9.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

