[build]
  base = "."
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_SERVER_URL = "https://your-backend-url.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
